Download Dataset
UdL-EPS-SoftArch/AgridataHub-API pull request #68
Opened 2021-01-24 22:52 UTC by jorgics

2021-01-25 08:03 UTC, bergacat1 approved these changes

2021-01-25 08:18 UTC, bergacat1 requested changes
Your tests are failing. Since there is not an accepted DatasetRequest for the Dataset you created, the API is responding with a 403 code. In fact, that's what you should be testing. But you also need to test the favourable case.

2021-01-25 20:53 UTC, rogargon commented
Please @jorgics fix the tests so the PR can be accepted and your previous commits considered for 3rd sprint

2021-01-26 08:14 UTC, rogargon approved these changes

2021-01-26 08:14 UTC, merged